services:
  # Laravel Application
  app:
    build:
      context: ../../
      dockerfile: docker/Dockerfile.volume
    container_name: laravel_app_test
    restart: unless-stopped
    volumes:
      - ./.env.local:/var/www/.env
      - app_files:/var/www
    # depends_on:
      # - db

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_test
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - app_files:/var/www
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: laravel_db_test
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  # Redis for sessions and caching
  redis:
    image: redis:alpine
    container_name: laravel_redis_test
    restart: unless-stopped

volumes:
  app_files: