FROM alpine:latest
RUN apk add --no-cache openssl

COPY scripts/cert-local/generate_cert.sh /usr/local/bin/generate_cert.sh

RUN chmod +x /usr/local/bin/generate_cert.sh

CMD ["/usr/local/bin/generate_cert.sh"]